# ################
# # LOCAL MODELS #
# ################

OutlinesFramework:
  - task: "synthetic_data_generation"
    n_runs: 100
    init_kwargs:
      prompt: "Generate a random person's information. The name must be chosen at random. Make it something you wouldn't normally choose.\nRespond in the following json schema: {json_schema}\n"
      llm_model: "meta-llama/Llama-3.1-8b-Instruct"
      llm_model_family: "transformers"
      max_length: 4096
  - task: "function_calling"
    n_runs: 10
    init_kwargs:
      source_data_pickle_path: "data/function_calling.pkl"
      llm_model: "meta-llama/Llama-3.1-8b-Instruct"
      llm_model_family: "transformers"
      max_length: 4096
      sample_rows: 100

LMFormatEnforcerFramework:
  - task: "synthetic_data_generation"
    n_runs: 100
    init_kwargs:
      prompt: "Generate a random person's information. The name must be chosen at random. Make it something you wouldn't normally choose.\nRespond in the following json schema: {json_schema}\n"
      llm_model: "meta-llama/Llama-3.1-8b-Instruct"
      llm_model_family: "transformers"
      max_length: 4096
  - task: "function_calling"
    n_runs: 10
    init_kwargs:
      source_data_pickle_path: "data/function_calling.pkl"
      llm_model: "meta-llama/Llama-3.1-8b-Instruct"
      llm_model_family: "transformers"
      max_length: 4096
      sample_rows: 100

PSEFramework:
  - task: "synthetic_data_generation"
    n_runs: 100
    init_kwargs:
      prompt: "Generate a random person's information. The name must be chosen at random. Make it something you wouldn't normally choose.\nRespond in the following json schema: {json_schema}\n"
      llm_model: "meta-llama/Llama-3.1-8b-Instruct"
      llm_model_family: "transformers"
      max_length: 4096
  - task: "function_calling"
    n_runs: 10
    init_kwargs:
      source_data_pickle_path: "data/function_calling.pkl"
      llm_model: "meta-llama/Llama-3.1-8b-Instruct"
      llm_model_family: "transformers"
      max_length: 4096
      sample_rows: 100
