################
# LOCAL MODELS #
################

OutlinesFramework:
  - task: "multilabel_classification"
    n_runs: 10
    init_kwargs:
      prompt: "Classify the following text: {text}.\nRespond in the following json schema: {json_schema}:\n"
      llm_model: "meta-llama/Llama-3.2-3B-Instruct"
      llm_model_family: "transformers"
      retries: 0 # Oulines transformers has no retry parameter
      source_data_pickle_path: "data/multilabel_classification.pkl"
      max_length: 4096
      sample_rows: 2
  - task: "ner"
    n_runs: 10
    init_kwargs:
      prompt: "Extract and resolve a list of entities from the following text: {text}.\nRespond in the following json schema: {json_schema}:\n"
      llm_model: "meta-llama/Llama-3.2-3B-Instruct"
      llm_model_family: "transformers"
      retries: 0
      source_data_pickle_path: "data/ner.pkl"
      sample_rows: 2
  - task: "synthetic_data_generation"
    n_runs: 10
    init_kwargs:
      prompt: "Generate a random person's information. The name must be chosen at random. Make it something you wouldn't normally choose.\nRespond in the following json schema: {json_schema}:\n"
      llm_model: "meta-llama/Llama-3.2-3B-Instruct"
      llm_model_family: "transformers"
      max_length: 4096

LMFormatEnforcerFramework:
  - task: "multilabel_classification"
    n_runs: 10
    init_kwargs:
      prompt: "Classify the following text: {text}.\nRespond in the following json schema: {json_schema}:\n"
      llm_model: "meta-llama/Llama-3.2-3B-Instruct"
      llm_model_family: "transformers"
      retries: 0
      source_data_pickle_path: "data/multilabel_classification.pkl"
      max_length: 4096
      sample_rows: 2
  - task: "ner"
    n_runs: 10
    init_kwargs:
      prompt: "Extract and resolve a list of entities from the following text: {text}.\nRespond in the following json schema: {json_schema}:\n"
      llm_model: "meta-llama/Llama-3.2-3B-Instruct"
      llm_model_family: "transformers"
      retries: 0
      source_data_pickle_path: "data/ner.pkl"
      max_length: 4096
      sample_rows: 2
  - task: "synthetic_data_generation"
    n_runs: 10
    init_kwargs:
      prompt: "Generate a random person's information. The name must be chosen at random. Make it something you wouldn't normally choose.\nRespond in the following json schema: {json_schema}:\n"
      llm_model: "meta-llama/Llama-3.2-3B-Instruct"
      llm_model_family: "transformers"
      max_length: 4096

PSEFramework:
  - task: "multilabel_classification"
    n_runs: 10
    init_kwargs:
      prompt: "Classify the following text: {text}.\nRespond in the following json schema: {json_schema}:\n"
      llm_model: "meta-llama/Llama-3.2-3B-Instruct"
      llm_model_family: "transformers"
      retries: 0 # PSE needs no retries
      source_data_pickle_path: "data/multilabel_classification.pkl"
      max_length: 4096
      sample_rows: 2
  - task: "ner"
    n_runs: 10
    init_kwargs:
      prompt: "Extract and resolve a list of entities from the following text: {text}.\nRespond in the following json schema: {json_schema}:\n"
      llm_model: "meta-llama/Llama-3.2-3B-Instruct"
      llm_model_family: "transformers"
      retries: 0 # PSE needs no retries
      source_data_pickle_path: "data/ner.pkl"
      sample_rows: 2
  - task: "synthetic_data_generation"
    n_runs: 10
    init_kwargs:
      prompt: "Generate a random person's information. The name must be chosen at random. Make it something you wouldn't normally choose.\nRespond in the following json schema: {json_schema}:\n"
      llm_model: "meta-llama/Llama-3.2-3B-Instruct"
      llm_model_family: "transformers"
      max_length: 4096
